- name: variables
  hosts:  localhost
  connection: local
  vars:
    course: devops with aws
    trainer: siva
    duration: 120hrs

  tasks:
  - name: variables define
    ansible.builtin.debug:
      msg: "course is {{course}},Trainer is {{trainer}}00, Duration is {{ duration }}"
