- name: print vars
  hosts: local
  connection: local
  vars:
    course: Devops woth aws #play level
    Trainer: siva kumat
    Duration: 120 hrs
  tasks:
  - name: print variables
    vars:
      course: Devops  # task level
    ansible.builtin.debug:
      msg: "course is {{ course}}, Trainer is {{ Trainer }}, Duration is {{ Duration }}"

  - name: print variables
    
    ansible.builtin.debug:
      msg: "course is {{ course}}, Trainer is {{ Trainer }}, Duration is {{ Duration }}"