- name: vars with prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: Name
    prompt: Please enter your name
  - name: Age
    Prompt: Please enter your age

  tasks:
  - name: print vars with prompt
    ansible.builtin.debug:
      msg: "my name is {{ Name}}, and age is {{ Age }}"