- name: vars with prefer
  hosts: local
  connection: local
  # vars:
  #   GREET: "Play"
  # vars_files:
  # - info.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Please enter your name
  #   private: false

  tasks:
  - name: print prefernce
    # vars:
    #   GREET: "Task"
    ansible.builtin.debug:
      msg: Hello from {{ GREET }}

          
# args
# task