- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install and run nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"


  - name: install debian  
    ansible.builtin.apt:
      name: debian
      state: installed
    when: ansible_os_family == "Debian"