- name: print loops
  hosts: web
  become: yes
  tasks:
  - name: print loops
    ansible.builtin.package:
      name: "{{  item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "mysql",  state: "present" }
    - { name: 'git'   , state: 'present' }
    - { name: 'gcc' , state: 'absent'}