- name: filters
  hosts: local
  connection: local
  tasks:
  - name: check the filters
    ansible.builtin.debug:
      msg: " Hello {{ name | default ('Ramesh') }}"

  - name: check the list
    vars:
      fruits: "apple,banana, orange"
    ansible.builtin.debug:
     msg: " fruits are {{ fruits | split(',') }}"


  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 1 hr
        trainer: siva
    ansible.builtin.debug:
      msg: " course info is {{ course | dict2items }}"

  - name: convert lower to upper
    vars:
      name: Kavya KummitHA
    ansible.builtin.debug:
      msg: "Hi {{ name | lower }}"

  - name: convert upper to lower
    vars:
      name: kavya kummitha
    ansible.builtin.debug:
      msg: " Hello {{ name | upper }}"