- name: filters
  hosts: local
  connection: local
  tasks:
  - name: check the filters
    ansible.builtin.debug:
      msg: " Hello {{ name | default ('Ramesh') }}"

  - name: check the list
    vars:
      fruits: "apple,banana, orange"
    ansible.builtin.debug:
     msg: " fruits are {{ fruits | split(',') }}"


  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 1 hr
        trainer: siva
    ansible.builtin.debug:
      msg: " course info is {{ course | dict2items }}"

  - name: convert lower to upper
    vars:
      name: Kavya KummitHA
    ansible.builtin.debug:
      msg: "Hi {{ name | lower }}"

  - name: convert upper to lower
    vars:
      name: kavya kummitha
    ansible.builtin.debug:
      msg: " Hello {{ name | upper }}"

  - name: select the min
    vars:
      numbers: [1,89,54,32,100]
    ansible.builtin.debug:
      msg: "check the {{ numbers | min }}"

  - name: select the max
    vars:
      numbers: [98,21,1,100]
    ansible.builtin.debug:
      msg: "check the {{ numbers | max }}"

  - name: check ip address
    vars:
      ip: 23.75.234.273
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"